### ISSUE TITLE
binary

### ISSUE THREAD

**Issue by sennevb** [anonymousbitcoin/anon-full-node-wallet#14]
binary not included, anond and anon-cli are missing!

**Comment by Zerolimitscrypto** [comment]
I am having the same issue?
 any help out there?

**Comment by paustria87** [comment]
Same. Searched every file and found no **anond** and **anon-cli** (building on Ubuntu 18.04)

**Comment by thomasluis** [comment]
The Anon wallet and the Anon binaries are separate. For Linux and Windows, you can get the binaries in the Anon's [release section](https://github.com/anonymousbitcoin/anon/releases). For Mac, the .dmg file in the wallet's [release section](https://github.com/anonymousbitcoin/anon-full-node-wallet/releases) contains the full node wallet with the executable.
