### ISSUE TITLE
Wallet unresponsive and showing several errors in the terminal

### ISSUE THREAD

**Issue by Cuzzo86** [anonymousbitcoin/anon-full-node-wallet#16]
I'm running the wallet on Ubuntu 18.04.1 LTS and compiled the anond, anon-cli and AnonymousDesktopWallet-0.1.1.jar as instructed.
When I start the wallet with the `java -jar AnonymousDesktopWallet-0.1.1.jar` command I see a lot of errors in the output.

```
[Thread-32] [Wed Sep 12 23:11:58 CEST 2018] [ERROR] cant parse CPU precentage %CPU 
[Thread-32] [Wed Sep 12 23:11:58 CEST 2018] [ERROR] cant parse virtual MB sizeVSZ 
[Thread-32] [Wed Sep 12 23:11:58 CEST 2018] [ERROR] cant parse resident MB size RSS 
[Thread-32] [Wed Sep 12 23:11:58 CEST 2018] [INFO] Gathering of dashboard daemon status data done in 32ms. 
```
These 5 lines of errors keep showing up over and over again.

There's also the following error when starting the wallet:
```
[main] [Wed Sep 12 23:19:14 CEST 2018] [INFO] error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct rpc port)
```

my anon.conf looks like this

    rpcuser=xxxxxxxxx
    rpcpassword=XXXXXXXXXXX
    rpcallowip=127.0.0.1
    rpcport=7932
    txindex=1

I'm not sure if the wallet is lagging because of it still hasn't fully been synchronized or because of the errors.

please advise

**Comment by thomasluis** [comment]
The correct rpc port is 3130. This has been corrected in the readme in the latest [PR](https://github.com/anonymousbitcoin/anon-full-node-wallet/pull/21). Are you still having issues starting the wallet?
