### ISSUE TITLE
Gradlew issue

### ISSUE THREAD

**Issue by Glomerulus22** [anonymousbitcoin/anon-full-node-wallet#19]
Hello, I got a problem with this command: ./gradlew clean fatJar
When I use it there is the error:
> Task :compileJava 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
4 actionable tasks: 3 executed, 1 up-to-date

So I cannot set up my masternode because of this mistake.

I tried noe installation of Java- JER and JDC, new install of gralde too.

Could you help me please?

Thanks a lot.

**Comment by thomasluis** [comment]
> Hello, I got a problem with this command: ./gradlew clean fatJar
> When I use it there is the error:
> 
> > Task :compileJava
> > Note: Some input files use or override a deprecated API.
> > Note: Recompile with -Xlint:deprecation for details.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD SUCCESSFUL in 4s
> 4 actionable tasks: 3 executed, 1 up-to-date
> 
> So I cannot set up my masternode because of this mistake.
> 
> I tried noe installation of Java- JER and JDC, new install of gralde too.
> 
> Could you help me please?
> 
> Thanks a lot.

This is a warning in regards to the future release of gradle 5.0. It has no effect on the wallet and should not be preventing you from setting up a masternode. What issue are you having in regards to setting up a masternode? @Glomerulus22

**Comment by Glomerulus22** [comment]
Thomas, thanks, currently I have this error:
I still get this error: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

My anon/anon.conf in my **local computer**:
rpcuser=glomerulus22
rpcpassword=my password
rpcallowip=127.0.0.1
rpcport=3130
txindex=1

My anon/anon.conf in my **VPS**:
rpcuser=glomerulus22
rpcpassword=my password
rpcallowip=127.0.0.1
rpcport=3130
txindex=1
masternode=1
masternodeprivkey=keygen of MN
externalip=IP of VPS

Could you please tell me where is the problem? Thanks a lot.

**Comment by thomasluis** [comment]
This error is preventing you from starting the wallet? Where do you have your .jar executable? @Glomerulus22

**Comment by Glomerulus22** [comment]
No I can run the wallet normally, but I cant run my masternode...my wallet file is in my anon/src directory

**Comment by thomasluis** [comment]
So to be clear, you've already created your masternode, are able to see it in the My Masternodes panel, and are having trouble starting it from that panel? @Glomerulus22

**Comment by Glomerulus22** [comment]
I was also not able to execute these two commands -

# Make the JAR executable - Change "VERSION" with the actual Version number
chmod u+x build/libs/AnonymousDesktopWallet-VERSION.jar

# Copy the JAR Wallet into the src folder
cp build/libs/AnonymousDesktopWallet-VERSION.jar ~/anon/src/

 there was an error no such file or directory, so I manually copied wallet file into anon/src and it worked - do you think the problem can be there?

**Comment by thomasluis** [comment]
The issue seems to be not with the wallet itself but with the masternode on the vps. To better assist you, I'd like you to log into [discord](https://discord.gg/zDyb9T) and message our core developer Calypso, who can guide you through any issues you're having with the masternode. If you're still having issues with the wallet, please feel free to reopen this issue @Glomerulus22
