### ISSUE TITLE
Send ANON doesn't work

### ISSUE THREAD

**Issue by Nevercom** [anonymousbitcoin/anon-full-node-wallet#5]
I have tried testnet and Anon Wallet. when i open my wallet there are many Addresses starting with "An" with 12.5 Anons and mined status.
When i try to send Anons to another address, an error appears stating that the destination address is not valid and Anon wallets start with "b1, bx or zk".

I have also created a new Z Address and its the same.
Also, when i create a new B address, the newly created address Starts with "An" (not b1 or bx)

**Comment by thedon-chris** [comment]
FIXED WITH PR #6
